services:
  - type: web
    name: geoguessr-clone
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000