services:
  - type: web
    name: geoguessr-clone
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter  # You can change this to 'standard' or 'pro' if needed
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    # Render will automatically detect port 5000 from your Dockerfile EXPOSE directive